site_name: Elfsquad Docs
theme: 
  name: material
  logo: https://ems.elfsquad.io/assets/images/logo_white.png
  palette:  
    primary: black
    accent: blue
nav:
  - Overview:
    - 'Getting started': index.md
    - Models: models.md
  - 'REST API':
    - 'Getting started': api/start.md
    - Basic endpoints: api/endpoints-crud.md
    - Webhooks: api/webhooks.md
    - Configurator: api/configurator.md
    - 'Tutorial: Features': api/tutorial/features.md
    - 'Tutorial: Application Events': api/tutorial/applicationevents.md
    - 'Tutorial: Custom configurator in Angular': api/tutorial/angularconfigurator/angular_configurator.md
  - SDK:
    - 'Getting started': sdk/start.md
    - 'Acting on events': sdk/applicationevents.md
  - 'PyAPI (Python)':
    - 'Getting started': pyapi/start.md