site_name: Elfsquad Docs
theme: 
  name: material
  logo: https://ems.elfsquad.io/assets/images/logo_white.png
  palette:  
    primary: black
    accent: blue
nav:
  - Overview:
    - 'Getting started': index.md
    - Models: models.md
  - 'REST API':
    - 'Getting started': api/start.md
    - Basic endpoints: api/endpoints-crud.md
    - Webhooks: api/webhooks.md
    - Configurator: api/configurator.md
    - 'Tutorial: Features': api/tutorial/features.md
    - 'Tutorial: Application Events': api/tutorial/applicationevents.md    
  - SDK (C#):
    - 'Getting started': sdk/start.md
    - 'Acting on events': sdk/applicationevents.md
  - SDK (JS):
    - 'Getting started': lib/start.md
    - 'API defintion': lib/api-definition.md
    - 'Step-by-Step Tutorials':
        - 'Basic operations': lib/tutorials/basic-operations.md
        - 'Tutorial: Custom configurator in Angular': api/tutorial/angularconfigurator/angular_configurator.md
  - 'PyAPI (Python)':
    - 'Getting started': pyapi/start.md
markdown_extensions:
  - codehilite