site_name: Elfskot Docs
theme: readthedocs
nav:
  - Overview:
    - 'Getting started': index.md
    - Models: models.md
  - 'REST API':
    - 'Getting started': api/start.md
    - Basic endpoints: api/endpoints-crud.md
    #- Custom endpoints: api/endpoints-custom.md
    - 'Tutorial: Features': api/tutorial/features.md
    - 'Tutorial: Application Events': api/tutorial/applicationevents.md
    #- 'Tutorial: Feature properties': api/tutorial/features-properties.md
    #- 'Tutorial: CRM accounts': api/tutorial/crm-accounts.md
    #- 'Tutorial: Quotations': api/tutorial/quotations.md
  #- SDK:
    #- 'Getting started': sdk/start.md
    #- 'Tutorial: Features': sdk/tutorial/features.md
    #- 'Tutorial: Feature properties': sdk/tutorial/features-properties.md
    #- 'Tutorial: CRM accounts': sdk/tutorial/crm-accounts.md
    #- 'Tutorial: Quotations': sdk/tutorial/quotations.md