site_name: Elfsquad Docs
theme: 
  name: material
  logo: https://ems.elfsquad.io/assets/images/logo_white.png
  palette:  
    primary: black
    accent: blue
extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css
nav:
  - Introduction: 'index.md'
  - Authentication: 'authentication.md'
  - Data API: apis/data.md
  # - APIs:
  #   - Data API: apis/data.md
  #   - Configurator API: apis/configurator.md
  #   - Quotations API: apis/quotations.md
  #   - "[OLD] API V2": apis/apiv2.md
  - "EMS API":
    - Overview:
      - 'Getting started': ems/index.md
      - Models: ems/models.md
    - 'REST API':
      - 'Getting started': ems/api/start.md
      - Basic endpoints: ems/api/endpoints-crud.md
      - Webhooks: ems/api/webhooks.md
      - Configurator: ems/api/configurator.md
      - 'Tutorial: Features': ems/api/tutorial/features.md
      - 'Tutorial: Application Events': ems/api/tutorial/applicationevents.md    
    - SDK (C#):
      - 'Getting started': ems/sdk/start.md
      - 'Acting on events': ems/sdk/applicationevents.md
    - SDK (JS):
      - 'Getting started': ems/lib/start.md
      - 'API defintion': ems/lib/api-definition.md
      - 'Step-by-Step Tutorials':
          - 'Basic operations': ems/lib/tutorials/basic-operations.md
          - 'Tutorial: Custom configurator in Angular': ems/api/tutorial/angularconfigurator/angular_configurator.md
    - 'PyAPI (Python)':
      - 'Getting started': ems/pyapi/start.md
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences